export const Concerts = {
  '2022.': [
    { date: 'május 14.', location: 'Fertőszéplak', isoDate: '2022-05-14' },
    { date: 'május 14.', location: 'Fertőhomok', isoDate: '2022-05-14' },
    { date: 'május 7.', location: 'Baja', isoDate: '2022-05-07' },
    { date: 'május 1.', location: 'Fertőhomok', isoDate: '2022-05-01' },
  ],
  '2021.': [
    { date: 'szeptember 19.', location: 'Szentendre' },
    { date: 'szeptember 4.', location: 'Fertőhomok' },
    { date: 'július 3.', location: 'Fertőd' },
    { date: 'június 5.', location: 'Fertőhomok' },
  ],
  '2020.': [{ date: 'december 25.', location: 'Fertőhomok' }],
  '2019.': [
    { date: 'december 22.', location: 'Fertőhomok' },
    { date: 'december 15.', location: 'Sarród' },
    { date: 'november 30.', location: 'Fertőhomok' },
    { date: 'november 23.', location: 'Fertőd' },
    { date: 'augusztus 31.', location: 'Fertőhomok' },
    { date: 'augusztus 10.', location: 'Peresznye' },
    { date: 'július 6.', location: 'Hidegség' },
    { date: 'június 15.', location: 'Brdovec (Horvátország)' },
    { date: 'június 1.', location: 'Kisfalud' },
    { date: 'május 5.', location: 'Fertőhomok' },
    { date: 'április 13.', location: 'Homokbödöge' },
  ],
  '2018.': [
    { date: 'december 23.', location: 'Fertőhomok' },
    { date: 'december 1.', location: 'Kópháza' },
    { date: 'szeptember 29.', location: 'Fertőhomok' },
    { date: 'augusztus 31.', location: 'Fertőhomok' },
    { date: 'június 23.', location: 'Fertőhomok' },
    { date: 'június 2.', location: 'Fertőboz' },
    { date: 'május 6.', location: 'Fertőhomok' },
    { date: 'április 14.', location: 'Fertőhomok' },
    { date: 'március 24.', location: 'Fertőhomok' },
  ],
  '2017.': [
    { date: 'december 17.', location: 'Fertőhomok' },
    { date: 'november 18.', location: 'Mosonmagyaróvár' },
    { date: 'december 3.', location: 'Hidegség' },
    { date: 'szeptember 23.', location: 'Szentendre' },
    { date: 'szeptember 1.', location: 'Brdovec (Horvátország)' },
    { date: 'május 27.', location: 'Alsópáhok' },
    { date: 'május 20.', location: 'Fertőhomok' },
    { date: 'május 7.', location: 'Fertőhomok' },
    { date: 'április 22.', location: 'Fertőhomok' },
    { date: 'április 22.', location: 'Fertőhomok' },
    { date: 'március 3.', location: 'Sopron' },
  ],
  '2016.': [
    { date: 'december 18.', location: 'Fertőhomok' },
    { date: 'szeptember 3.', location: 'Fertőhomok' },
    { date: 'szeptember 2.', location: 'Fertőhomok' },
    { date: 'augusztus 12. Fertőd' },
    { date: 'július 2.', location: 'Illmitz (Ausztria)' },
    { date: 'május 23.', location: 'Dunaszeg' },
    { date: 'május 1.', location: 'Fertőhomok' },
    { date: 'április 23.', location: 'Prelog (Horvátország)' },
    { date: 'február 13.', location: 'Fertőhomok' },
    { date: 'január 23.', location: 'Hegykő' },
  ],
  '2015.': [
    { date: 'december 20.', location: 'Fertőhomok' },
    { date: 'november 14.', location: 'Fertőhomok' },
    { date: 'november 7.', location: 'Und' },
    { date: 'október 17.', location: 'Fertőhomok' },
    { date: 'szeptember 5.', location: 'Brdovec (Horvátország)' },
    { date: 'augusztus 30.', location: 'Fertőrákos' },
    { date: 'augusztus 1.', location: 'Fertőszéplak' },
    { date: 'június 20.', location: 'Devinsko Novo Selo (Szlovákia)' },
    { date: 'június 6.', location: 'Pereszteg' },
    { date: 'május 3.', location: 'Fertőhomok' },
    { date: 'április 25.', location: 'Fertőhomok' },
    { date: 'április 25.', location: 'Sarród' },
    { date: 'február 6.', location: 'Hegykő' },
  ],
  '2014.': [
    { date: 'december 21.', location: 'Fertőhomok' },
    { date: 'november 29.', location: 'Fertőszéplak' },
    { date: 'november 14.', location: 'Sopron' },
    { date: 'szeptember 13.', location: 'Fertőhomok' },
    { date: 'augusztus 3.', location: 'Mezőkövesd' },
    { date: 'július 27.', location: 'Fertőhomok' },
    { date: 'július 5.', location: 'Hidegség' },
    { date: 'június 28.', location: 'Fertőhomok' },
    { date: 'május 25.', location: 'Sopron' },
    { date: 'május 17.', location: 'Fertőhomok' },
    { date: 'május 4.', location: 'Fertőhomok' },
    { date: 'május 1.', location: 'Fertőd' },
    { date: 'április 27.', location: 'Hidegség' },
    { date: 'április 26.', location: 'Fertőhomok' },
    { date: 'március 1.', location: 'Hegykő' },
    { date: 'február 22.', location: 'Győrszentiván' },
    { date: 'február 14.', location: 'Hegykő' },
  ],
  '2013.': [
    { date: 'december 22.', location: 'Fertőhomok' },
    { date: 'november 16.', location: 'Fertőhomok' },
    { date: 'október 20.', location: 'Sobor' },
    { date: 'október 12.', location: 'Fertőhomok' },
    { date: 'szeptember 29.', location: 'Sopron' },
    { date: 'szeptember 22.', location: 'Bécs (Ausztria)' },
    { date: 'szeptember 15.', location: 'Fertőhomok' },
    { date: 'szeptember 13.', location: 'Hegykő' },
    { date: 'szeptember 7.', location: 'Brdovec (Horvátország)' },
    { date: 'augusztus 31.', location: 'Balf' },
    { date: 'július 6.', location: 'Fertőendréd' },
    { date: 'július 6.', location: 'Fertőhomok' },
    { date: 'június 21.', location: 'Sopron' },
    { date: 'június 15.', location: 'Fertőhomok' },
    { date: 'május 25.', location: 'Fertőboz' },
    { date: 'május 12.', location: 'Budapest' },
    { date: 'május 4.', location: 'Fertőhomok' },
    { date: 'március 8.', location: 'Sopron' },
    { date: 'január 25.', location: 'Hegykő' },
  ],
  '2012.': [
    { date: 'december 23.', location: 'Fertőhomok' },
    { date: 'december 1.', location: 'Fertőhomok' },
    { date: 'október 6.', location: 'Fertőhomok' },
    { date: 'szeptember 15.', location: 'Kópháza' },
    { date: 'augusztus 25.', location: 'Fertőhomok' },
    { date: 'augusztus 18.', location: 'Fertőhomok' },
    { date: 'augusztus 11.', location: 'Sarród' },
    { date: 'július 7.', location: 'Fertőhomok' },
    { date: 'július 7.', location: 'Sopron' },
    { date: 'július 7.', location: 'Hidegség' },
    { date: 'június 24.', location: 'Hegykő' },
    { date: 'június 9.', location: 'Fertőhomok' },
    { date: 'május 18.', location: 'Fertőhomok' },
    { date: 'május 12.', location: 'Bodonhely' },
    { date: 'április 28.', location: 'Fertőhomok' },
    { date: 'február 11.', location: 'Hegykő' },
    { date: 'január 21.', location: 'Szany' },
  ],
  '2011.': [
    { date: 'december 18.', location: 'Fertőhomok' },
    { date: 'december 3.', location: 'Tárnokréti' },
    { date: 'november 26.', location: 'Fertőhomok' },
    { date: 'november 12.', location: 'Nagycenk' },
    { date: 'szeptember 23.', location: 'Fertőszéplak' },
    { date: 'szeptember 10.', location: 'Bobovec (Horvátország)' },
    { date: 'szeptember 9.', location: 'Brdovec (Horvátország)' },
    { date: 'június 25.', location: 'Fertőhomok' },
    { date: 'május 21.', location: 'Fertőszéplak' },
    { date: 'május 7.', location: 'Hegykő' },
    { date: 'május 1.', location: 'Fertőhomok' },
    { date: 'január 21.', location: 'Hegykő' },
  ],
  '2010.': [
    { date: 'december 25.', location: 'Fertőhomok' },
    { date: 'november 13.', location: 'Kópháza' },
    { date: 'október 9.', location: 'Győr' },
    { date: 'augusztus 28.', location: 'Sarród' },
    { date: 'július 3.', location: 'Hidegség' },
    { date: 'június 20.', location: 'Pécs' },
    { date: 'június 12.', location: 'Und' },
    { date: 'június 11.', location: 'Fertőhomok' },
    { date: 'május 15.', location: 'Kapuvár' },
    { date: 'május 8.', location: 'Baja' },
    { date: 'január 22.', location: 'Hegykő' },
  ],
  '2009.': [
    { date: 'szeptember 12.', location: 'Beled' },
    { date: 'augusztus 21-22.', location: 'Fertőhomok' },
    { date: 'augusztus 15.', location: 'Budapest' },
    { date: 'június 20.', location: 'Balf' },
    { date: 'május 29.', location: 'Brdovec (Horvátország)' },
    { date: 'május 21.', location: 'Győr' },
    { date: 'május 3.', location: 'Fertőhomok' },
    { date: 'április 26.', location: 'Alsópáhok' },
    { date: 'február 21.', location: 'Fertőszentmiklós' },
    { date: 'január 17.', location: 'Hegykő' },
  ],
  '2008.': [
    { date: 'december 21.', location: 'Fertőhomok' },
    { date: 'november 22.', location: 'Filež (Ausztria)' },
    { date: 'november 15.', location: 'Dunaszerdahely (Felvidék)' },
    { date: 'szeptember 28.', location: 'Budapest' },
    { date: 'szeptember 20.', location: 'Ágfalva' },
    { date: 'szeptember 13.', location: 'Kópháza' },
    { date: 'szeptember 6.', location: 'Hegykő' },
    { date: 'július 27.', location: 'Fertőhomok' },
    { date: 'június 15.', location: 'Fertőrákos' },
    { date: 'június 7.', location: 'Nyárliget' },
    { date: 'május 31.', location: 'Győr' },
    { date: 'május 23.', location: 'Fertőhomok' },
    { date: 'április 19.', location: 'Nagycenk' },
    { date: 'április 13.', location: 'Eisenstadt (Ausztria)' },
    { date: 'március 7.', location: 'Zaprešić (Horvátország)' },
    { date: 'január 25.', location: 'Hegykő' },
  ],
  '2007.': [
    { date: 'december 22.', location: 'Fertőhomok' },
    { date: 'december 15.', location: 'Mosonmagyaróvár' },
    { date: 'szeptember 23.', location: 'Bécs (Ausztria)' },
    { date: 'augusztus 31.', location: 'Fertőhomok' },
    { date: 'július 29.', location: 'Fertőhomok (lemezbemutató koncert)' },
    { date: 'július 21.', location: 'Fertőrákos' },
    { date: 'június 23.', location: 'Fertőd' },
    { date: 'június 16.', location: 'Hidegség' },
    { date: 'május 20.', location: 'Győr' },
    { date: 'május 5.', location: 'Fertőhomok' },
    { date: 'április 27.', location: 'Brdovec (Horvátország)' },
    { date: 'január 26.', location: 'Hegykő' },
  ],
  '2006.': [
    { date: 'december 17.', location: 'Fertőhomok' },
    { date: 'november 25.', location: 'Győr' },
    { date: 'november 24.', location: 'Fertőd' },
    { date: 'november 19.', location: 'Győr' },
    { date: 'október 7.', location: 'Győr' },
    { date: 'szeptember 30.', location: 'Fertőd' },
    { date: 'szeptember 16.', location: 'Győr' },
    { date: 'augusztus 11-12-13.', location: 'Fertőhomok' },
    { date: 'július 8-9.', location: 'Đakovo (Horvátország)' },
    { date: 'július 1.', location: 'Fertőhomok' },
    { date: 'június 24.', location: 'Győr' },
    { date: 'június 17.', location: 'Hidegség' },
    { date: 'június 3.', location: 'Nagylózs' },
    { date: 'május 27.', location: 'Bezenye' },
    { date: 'május 19.', location: 'Fertőhomok' },
    { date: 'március 11.', location: 'Fertőszentmiklós' },
    { date: 'március 11.', location: 'Kapuvár' },
    { date: 'január 27.', location: 'Hegykő' },
  ],
  '2005.': [
    { date: 'november 25.', location: 'Fertőd' },
    { date: 'november 19.', location: 'Hegykő' },
    { date: 'november 13.', location: 'Fertőhomok' },
    { date: 'november 12.', location: 'Sopron' },
    { date: 'november 6.', location: 'Győr' },
    { date: 'november 5.', location: 'Kőszeg' },
    { date: 'október 15.', location: 'Und' },
    { date: 'szeptember 10.', location: 'Fertőhomok' },
    { date: 'szeptember 10.', location: 'Fertőd' },
    { date: 'augusztus 27.', location: 'Balf' },
    { date: 'augusztus 20.', location: 'Alsópulya (Ausztria)' },
    { date: 'augusztus 13.', location: 'Fertőhomok' },
    { date: 'augusztus 13.', location: 'Fertőszéplak' },
    { date: 'augusztus 7.', location: 'Filež (Ausztria)' },
    { date: 'augusztus 6.', location: 'Nagycenk' },
    { date: 'július 30.', location: 'Peresznye' },
    { date: 'július 23.', location: 'Hegykő' },
    { date: 'július 22.', location: 'Hegykő' },
    { date: 'július 9.', location: 'Kópháza' },
    { date: 'június 26.', location: 'Sopron' },
    { date: 'június 18.', location: 'Devinsko Novo Selo (Szlovákia)' },
    { date: 'május 21.', location: 'Budapest' },
    { date: 'május 13.', location: 'Brdovec (Horvátország)' },
    { date: 'május 7.', location: 'Fertőhomok' },
    { date: 'február 5.', location: 'Hegykő' },
    { date: 'január 22.', location: 'Fertőd' },
    { date: 'január 21.', location: 'Hegykő' },
  ],
  '2004.': [
    { date: 'december 19.', location: 'Fertőhomok' },
    { date: 'november 26.', location: 'Fertőd' },
    { date: 'november 19.', location: 'Hegykő' },
    { date: 'november 13.', location: 'Hegykő' },
    { date: 'november 6.', location: 'Sopron' },
    { date: 'október 2.', location: 'Sárvár' },
    { date: 'szeptember 25.', location: 'Fertőhomok' },
    { date: 'szeptember 12.', location: 'Sopronbánfalva' },
    { date: 'szeptember 5.', location: 'Ólmod' },
    { date: 'augusztus 15.', location: 'Ruszt (Ausztria)' },
    { date: 'július 25.', location: 'Fertőhomok' },
    { date: 'július 23.', location: 'Bük' },
    { date: 'július 10.', location: 'Sopron' },
    { date: 'június 26.', location: 'Und' },
    { date: 'június 11.', location: 'Fertőhomok' },
    { date: 'június 5.', location: 'Gersekarát' },
    { date: 'május 29.', location: 'Kimle' },
    { date: 'május 23.', location: 'Fertőboz' },
    { date: 'május 14.', location: 'Fertőhomok' },
    { date: 'május 7.', location: 'Fertőhomok' },
    { date: 'május 2.', location: 'Fertőhomok' },
    { date: 'május 1.', location: 'Balf' },
    { date: 'május 1.', location: 'Sopron' },
    { date: 'április 30.', location: 'Harka' },
    { date: 'március 19.', location: 'Sopron' },
    { date: 'január 23.', location: 'Hegykő' },
    { date: 'január 17.', location: 'Csepreg' },
  ],
  '2003.': [
    { date: 'november 22.', location: 'Fertőszentmiklós' },
    { date: 'november 22.', location: 'Hegykő' },
    { date: 'november 16.', location: 'Fertőhomok' },
    { date: 'november 15.', location: 'Hegykő' },
    { date: 'november 8.', location: 'Baja' },
    { date: 'október 18.', location: 'Tököl' },
    { date: 'szeptember 27.', location: 'Fertőhomok' },
    { date: 'szeptember 21.', location: 'Bécs (Ausztria)' },
    { date: 'szeptember 20.', location: 'Fertőújlak' },
    { date: 'szeptember 6.', location: 'Csorna' },
    { date: 'augusztus 17.', location: 'Szentpéterfa' },
    { date: 'július 19.', location: 'Fertőrákos' },
    { date: 'július 6.', location: 'Hidegség' },
    { date: 'június 28.', location: 'Bük' },
    { date: 'június 1.', location: 'Hegykő' },
    { date: 'május 31.', location: 'Farád' },
    { date: 'május 25.', location: 'Fertőboz' },
    { date: 'május 24.', location: 'Nagycenk' },
    { date: 'május 18.', location: 'Fertőd' },
    { date: 'május 16.', location: 'Brdovec (Horvátország)' },
    { date: 'május 4.', location: 'Fertőhomok' },
    { date: 'április 20.', location: 'Und' },
    { date: 'április 6.', location: 'Fertőd' },
    { date: 'április 5.', location: 'Dunaszeg' },
    { date: 'március 16.', location: 'Fertőhomok' },
    { date: 'február 15.', location: 'Fertőhomok' },
  ],
  '2002.': [
    { date: 'december 22.', location: 'Fertőhomok' },
    { date: 'november 21.', location: 'Fertőhomok' },
    { date: 'november 4.', location: 'Budapest' },
    { date: 'szeptember 8.', location: 'Hegykő' },
    { date: 'július 28.', location: 'Fertőhomok' },
    { date: 'július 20.', location: 'Fertőrákos' },
    { date: 'június 22.', location: 'Hegykő' },
    { date: 'május 31.', location: 'Csorna' },
    { date: 'május 5.', location: 'Fertőhomok' },
    { date: 'április 26.', location: 'Fertőhomok' },
    { date: 'március 1.', location: 'Győr' },
    { date: 'február 3.', location: 'Fertőszentmiklós' },
    { date: 'január 26.', location: 'Fertőhomok' },
  ],
  '2001.': [
    { date: 'december 23.', location: 'Fertőhomok' },
    { date: 'november 25.', location: 'Fertőendréd' },
    { date: 'november 17.', location: 'Baja' },
    { date: 'november 11.', location: 'Fertőhomok' },
    { date: 'augusztus 18.', location: 'Iván' },
    { date: 'augusztus 5.', location: 'Hegykő' },
    { date: 'augusztus 5.', location: 'Fertőhomok' },
    { date: 'június 16.', location: 'Und' },
    { date: 'június 3.', location: 'Hidegség' },
    { date: 'május 27.', location: 'Fertőhomok' },
    { date: 'május 6.', location: 'Fertőhomok' },
    { date: 'május 1.', location: 'Fertőhomok' },
    { date: 'április 21.', location: 'Brdovec (Horvátország)' },
    { date: 'február 17.', location: 'Fertőd' },
  ],
  '2000.': [
    { date: 'december 22.', location: 'Fertőhomok' },
    { date: 'november 19.', location: 'Fertőhomok' },
    { date: 'november 18.', location: 'Hegykő' },
    { date: 'november 7.', location: 'Fertőhomok' },
    { date: 'október 14.', location: 'Mohács' },
    { date: 'szeptember 10.', location: 'Sarród' },
    { date: 'szeptember 2.', location: 'Balf' },
    { date: 'augusztus 19.', location: 'Kópháza' },
    { date: 'augusztus 6.', location: 'Hidegség' },
    { date: 'július 8.', location: 'Und' },
    { date: 'május 20.', location: 'Fertőhomok' },
    { date: 'május 7.', location: 'Fertőhomok' },
  ],
  '1999.': [{ date: 'december 18.', location: 'Fertőhomok' }],
};
