import { Disks } from "models";

export const disks: Disks = {
  desetZlatnihGodina: {
    title: '10 zlatnih godina (2009.)',
    tracks: {
      'antunovo-kolo': { title: 'Antunovo kolo', music: 'J. Szallmer' },
      'nase-korijenje': {
        title: 'Naše korijenje',
        lyrics: 'M. Dekić',
        music: 'J. Szallmer',
        text: [
          'Naše korijenje iz Matice niče',
          'Ona nam je vrelo stoljetnih sanja',
          'Domovinu ljubit Hrvat ne poriče',
          'U njojzi mu nada, vjera bitisanja.',
          '',
          "Hajd'mo skupa zaigrati,",
          "Nek' se znade nek' se pamti:",
          'Ovdje su živjeli, jošte ovdje žive,',
          'I živjet će Hrvati!',
          '',
          'Zdravo da ste Bunjevci, Podravci',
          'Međimurci, Šokci, Gradišćanci,',
          'Dalmatinci, Bošnjaci i Raci,',
          'Vjerni sinci Hrvatskoj nam majci!',
          '',
          'U jeziku svome rod navijek se štiti,',
          "Kolo j' sunce što ga čuva, grije.",
          'Ravnom Panonijom groblja će nam biti,',
          'Potomstvo korijenje zatajiti ne smije!',
          '',
          "Hajd'mo skupa zaigrati,",
          "Nek' se znade nek' se pamti:",
          'Ovdje su živjeli, jošte ovdje žive,',
          'I živjet će Hrvati!',
        ],
      },
      'nisam-vrijedan-suza': {
        title: 'Nisam vrijedan suza',
        lyrics: 'J. Szallmer',
        music: 'J. Szallmer',
        text: [
          'Željno si mene čekala',
          'Bila si oduševljena',
          'Sjećam se one zime, zvon zvonio ti ime',
          'Pale su bijele pahulje.',
          '',
          'Znao sam da neću dolazit,',
          'Da ću ti srce razgazit.',
          'Te tvoje plave oči, ove ledene noći',
          'Neće me više vidjeti.',
          '',
          'Nemoj zbog mene plakati',
          'Nemoj ni suzu lijati',
          'Tvog srca nisam vrijedan, ljubavi nisam žedan',
          'Ne trebaš mi ni oprostiti.',
          '',
          'Ne treba da mi zamjeriš',
          'Na me da svašta govoriš.',
          'Srce mi studen kamen, nema u njemu plamen',
          'Most ljubavi je razrušen.',
          '',
          'Večernji zvon kad zazvoni',
          "Božji mir nek' ti pokloni.",
          'Sklopi si svoje ruke, zaboravi sve tuge',
          'Sve tužne noći preduge.',
          '',
          'Nemoj zbog mene...',
        ],
      },
      ti: {
        title: 'Ti',
        lyrics: 'J. Szallmer',
        music: 'J. Szallmer',
        text: [
          'Ti si mirno, zlatno veče',
          'Ti si najslađi moj san',
          'Tražim tebe svakog jutra',
          'Kad me ne dirne tvoj dlan.',
          '',
          'A ti, a ti me ne voliš',
          'A ti, za drugim poludiš',
          'A ti, a ti ćeš biti moja',
          'Bit ćeš moja kad se smiriš.',
          '',
          'Ti si moja noćna zvijezda',
          'Najljepša na nebu si',
          'Sunce ne blistaše tako',
          "K'o kad na me gledaš ti.",
          '',
          'A ti, a ti...',
          '',
          'Volim tvoju dugu kosu',
          'Oči tvoje zelene',
          'Žarka i rumena usna',
          'I poljupce žerave.',
          '',
          'A ti, a ti...',
          '',
          "Ja b' te držao u ruci",
          'Kao cvijeće mirisno',
          'Koje nikad bacit neću',
          'Voljet ću je zanosno!',
          '',
          'A ti, a ti...',
        ],
      },
      'o-plavo-more': {
        title: 'O plavo more',
        lyrics: 'J. Szallmer',
        music: 'J. Szallmer',
        text: [
          'Kad zora se budi, ti još mirno spiš',
          "Sa obale gledam te, k'o polje se raširiš",
          'Tiho si i mirno, slušam tvoj dah',
          'Ne vjerujem kad čujem da možeš dati i strah.',
          '',
          'O plavo more, more Jadransko',
          'Silno si more, more duboko.',
          'O plavo more, najlipše na svitu si ti',
          'Ja te nikad neću, ne mogu zaboraviti.',
          '',
          'Ti usnivaš čamce kad spušta se noć',
          'Gitare glas čeka na nas, vrime za feštu će doć',
          'Zapjevajmo pjesme, pjesme o ljubavi',
          'Pjevamo svi, pjevaš i ti, a sviraju i valovi.',
          '',
          'O plavo more, more Jadransko',
          'Silno si more, more duboko.',
          'O plavo more, najlipše na svitu si ti',
          'Ja te nikad neću, ne mogu zaboraviti.',
        ],
      },
      'daj-mi-vina': {
        title: 'Daj mi vina',
        lyrics: 'J. Szallmer',
        music: 'J. Szallmer',
        text: [
          "Zasvirat ću do zore, svi nek' pjevaju",
          'Žice neka pucaju, a cure igraju.',
          'Daj još mi vina, dušu da poliva i srce mi razveseli.',
          'Rakiju toči ove divne noći, i lako ćemo sve preživjeti.',
          '',
          'Životu još nije kraj, daj i uživaj',
          'Lumpuj, sviraj i pjevaj, idemo u raj.',
          'Daj još mi vina, dušu da poliva i srce mi razveseli.',
          'Rakiju toči ove divne noći, i lako ćemo sve preživjeti.',
          '',
          'Dođi moja jedina, curo garava,',
          'Neka cijelo selo zna, da te ljubim ja.',
          'Daj još mi vina, dušu da poliva i srce mi razveseli.',
          'Rakiju toči ove divne noći, i lako ćemo sve preživjeti.',
          '',
          "Plešimo uz tambure, pa nek' vide svi",
          'Kako treba živjeti, cure ljubiti.',
          'Daj još mi vina, dušu da poliva i srce mi razveseli.',
          'Rakiju toči ove divne noći, i lako ćemo sve preživjeti.',
        ],
      },
      'pijem-i-placem': {
        title: 'Pijem i plačem',
        lyrics: 'J. Szallmer',
        music: 'J. Szallmer',
        text: [
          'Bila si mala, pa velika',
          'Kad si mi srce zauzela',
          'Cijeli si život me pratila',
          'Pa si na kraju zašutila.',
          '',
          'Dala si ljubav i srcu bol',
          'Nekad mi glava pala na stol',
          'Cijeli si život me pratila',
          'Pa si na kraju zašutila.',
          '',
          'Pijem i plačem kad nema te',
          'Pijem i plačem bez tebe',
          'Pijem i plačem kriva si ti',
          'Da moram piti i plakati.',
          '',
          'Tebe su ruke milovale',
          'Plave su oči zasuzile',
          'Cijeli si život me pratila',
          'Pa si na kraju zašutila.',
          '',
          'Vjerna si bila do zadnjega',
          "Volio sam te k'o nikoga",
          'Cijeli si život me pratila',
          'Pa si na kraju zašutila.',
          '',
          'Pijem i plačem...',
          '',
          'Slabe te ruke ne diraju',
          'Pjesme se više ne sviraju',
          'Cijeli si život me pratila',
          'Pa si na kraju zašutila.',
          '',
          'Gledam te, gledam i dobro znam',
          'Bez glasa tvoga ostajem sam.',
          'Cijeli si život me pratila',
          'Pa si na kraju zašutila.',
          '',
          'Pijem i plačem...',
        ],
      },
      'moj-mili-dom': {
        title: 'Moj mili dom',
        lyrics: 'J. Szallmer',
        music: 'J. Szallmer',
        text: [
          'Selo je moje maleno',
          'I već odavno stvoreno',
          'Zgradjeno, gnjezdo, hrvatsko.',
          '',
          'Otkada sam se rodio',
          'Domaćom pjesmom se hranio',
          'Družio, igrao, veselio.',
          '',
          'Gizdav sam da Hrvat sam',
          'Sin naroda svog.',
          'Moje selo, mili dom',
          'Sačuvaj mi Bog!',
          '',
          'Naša je "Gora" zelena',
          'Med svima najzelenija',
          'Gledajte, volite, nedajte!',
          '',
          'Malo nas ima premalo,',
          "Al' svoje nikad nedajmo!",
          'Čuvajmo, branimo, gajimo!',
          '',
          'Gizdav sam da Hrvat sam',
          'Sin naroda svog.',
          'Moje selo, mili dom',
          'Sačuvaj mi Bog!',
        ],
      },
      tuga: { title: 'Tuga', music: 'Á. Horváth' },
      'izjava-ljubavi': {
        title: 'Izjava ljubavi',
        lyrics: 'J. Szallmer',
        music: 'Á. Horváth',
        text: [
          'Volim tvoj miris i oka ti sjaj,',
          "K'o plavo more i zeleni gaj.",
          'Mislim na tebe, kad zaigra noć,',
          'Čekam te ja, kad kuca polnoć.',
          '',
          'Ti, ti si mi jedino sve,',
          'Ne mogu ja bez tebe.',
          'Snagu mi daješ, kad zadani dan,',
          'Ti si i slatki moj san.',
          '',
          'Rosa u travi da si mi ti,',
          'U tebi hoću se umivati.',
          'Da si ti cvijet mile ruže moje,',
          'Suzama lijevao bi ja tebe.',
          '',
          'Ti, ti si mi jedino sve,',
          'Ne mogu ja bez tebe.',
          'Snagu mi daješ, kad zadani dan,',
          'Ti si i slatki moj san.',
          '',
          'Molim te, molim te, ljubav mi daj,',
          'Čekat će nas dvoje nebeski raj.',
          'Ja ću te dušo zagrliti,',
          'Sudbina neće nas rastaviti.',
          '',
          'Ti, ti si mi jedino sve,',
          'Ne mogu ja bez tebe.',
          'Snagu mi daješ, kad zadani dan,',
          'Ti si i slatki moj san.',
        ],
      },
      'joskino-kolo': {
        title: 'Joškino kolo',
        music: 'J. Szallmer',
      },
      'zadnju-mi-pjesmu-svirajte': {
        title: 'Zadnju mi pjesmu svirajte',
        lyrics: 'J. Szallmer',
        music: 'J. Szallmer',
        text: [
          'Pjesma je druga ljubav moja',
          'Prva me je brzo ostavila',
          'Druga me cijeli život pratila',
          'I čuvala kao dobra vila.',
          '',
          "Ja sam joj dao što sam mog'o",
          'I popio sam dobra vina naša',
          'Pjevao sam s puno ljubavi',
          'Pratilo me puno tamburaša.',
          '',
          'Zadnju mi pjesmu svirajte',
          'Neka čuju prijatelji naši',
          'Kako pjeva stari tamburaš',
          'Kad ga prate svoji tamburaši.',
          '',
          'U životu ništa nisam imao',
          'Ništa, samo raspjevanu dušu',
          'I gorke suze u očima,',
          'Pa snove koji uvijek mi se rušu.',
          '',
          'Otišli su prijatelji stari',
          'Sve se ljepote zaboravile',
          'Tiho mi još svira tambura,',
          'Tiho, ali meni najmilije.',
          '',
          'Zadnju mi pjesmu svirajte',
          'Neka čuju prijatelji naši',
          'Kako pjeva stari tamburaš',
          'Kad ga prate svoji tamburaši.',
        ],
      },
      'jednoj-uciteljici': {
        title: 'Jednoj učiteljici',
        lyrics: 'M. Dekić',
        music: 'J. Szallmer',
        text: [
          'Pokraj rijeke koja mrmoreći teče',
          'S kime dočekuješ tih sumrak i veče,',
          'S kime dočekuješ tih sumrak i veče,',
          'Pokraj rijeke koja mrmoreći teče?',
          '',
          'Da li imaš koga da nad tobom bdije,',
          'Da te strasno voli, brani, čuva i krije,',
          'Da te strasno voli, brani, čuva i krije,',
          'Da li imaš koga da nad tobom bdije?',
          '',
          'Kome li sad plačeš suze radosnice,',
          'Ko ti miluje kose i ljupko lice,',
          'Ko ti miluje kose i ljupko lice,',
          'Kome li sad plačeš suze radosnice?',
          '',
          'Da li imaš koga u mjeseca sjaju,',
          'Da ti ljubi usne u toplom zagrljaju,',
          'Da ti ljubi usne u toplom zagrljaju,',
          'Da li imaš koga u mjeseca sjaju?',
          '',
          'Ma s kim budeš prošla kroz radost i tugu,',
          'Neću imat snage tražit bolju, drugu,',
          'Neću imat snage tražit bolju, drugu,',
          'Ma s kim budeš prošla kroz radost i tugu?',
        ],
      },
      'tamburo-sviraj': {
        title: 'Tamburo, sviraj!',
        lyrics: 'J. Szallmer',
        music: 'J. Szallmer',
        text: [
          'Hladna je večer, jesen dolazi',
          "Grana mog' stabla umira.",
          'Magla se spušta, rosne mi oči,',
          'Ni jedna ptica ne pjeva.',
          '',
          'Ej, tamburo sviraj, samo tiho sviraj!',
          'Ti si moja jedna jedina.',
          'Ej, tamburo sviraj, a nju usnivaj',
          'Da me u snu bude voljela.',
          '',
          'Žarko je ljeto grijalo dušu',
          "Ljubav u srcu j' duboka.",
          'Dalo mi svjetlo, mirisnu ružu',
          'I pogled plavog oka.',
          '',
          'Ej, tamburo sviraj, samo tiho sviraj!',
          'Ti si moja jedna jedina.',
          'Ej, tamburo sviraj, a nju usnivaj',
          'Da me u snu bude voljela.',
          '',
          'Šuma sad šuti, krije mi snove',
          'Pjesma se moja ne pjeva.',
          'Šute i ljudi, svi oko mene',
          'Snijeg bijeli život pokriva.',
          '',
          'Ej, tamburo sviraj, samo tiho sviraj!',
          'Ti si moja jedna jedina.',
          'Ej, tamburo sviraj, a nju usnivaj',
          'Da me u snu bude voljela.',
        ],
      },
      milena: {
        title: 'Milena',
        lyrics: 'J. Szallmer',
        music: 'J. Szallmer',
        text: [
          'Zora si, što mene budi,',
          'Jutro, koje dan mi nudi.',
          'A po danu tebe vidim bilo kud gledam.',
          'Večerom kad sunce zađe,',
          'Pogled moj te opet nađe',
          'A u noći tebe sanjam, tebe dozivam.',
          '',
          'Milena, Milena, prekrasna ti crna kosa dugačka.',
          'Milena, Milena, sve si ono što je želja momačka.',
          '',
          'Kad zagledam tvoje oči,',
          'Nemam dana, nemam noći.',
          "Pogled tvoj u srce puca, mira mi ne da'.",
          'Miris tvoj kad ja osjetim',
          'Hoću odmah da poludim,',
          'Ime tvoje zaboravit neću nikada.',
          '',
          'Milena, Milena, prekrasna ti crna kosa dugačka.',
          'Milena, Milena, sve si ono što je želja momačka.',
          '',
          'Živim da te stalno ljubim',
          'Nikad da te ne izgubim,',
          'Da po danu i po noći poljupce ti dam.',
          'Nemoj meni ništa reći,',
          'Oči su ti govoreći.',
          'Ovu pjesmu, želim tebi uvijek, da pjevam.',
          '',
          'Milena, Milena, prekrasna ti crna kosa dugačka.',
          'Milena, Milena, sve si ono što je želja momačka.',
        ],
      },
      ljubav: {
        title: 'Ljubav',
        lyrics: 'J. Szallmer',
        music: 'J. Szallmer',
        text: [
          'Volim tvoj miris i oka ti sjaj,',
          "K'o plavo more i zeleni gaj.",
          'Mislim na tebe, kad zaigra noć,',
          'Čekam te ja, kad kuca polnoć.',
          '',
          'Ti, ti si mi jedino sve,',
          'Ne mogu ja bez tebe.',
          'Snagu mi daješ, kad zadani dan,',
          'Ti si i slatki moj san.',
          '',
          'Rosa u travi da si mi ti,',
          'U tebi želim se umivati.',
          'Da si ti cvijet mile ruže moje,',
          'Sa suzama lijevao bi ja tebe.',
          '',
          'Ti, ti si mi jedino sve,',
          'Ne mogu ja bez tebe.',
          'Snagu mi daješ, kad zadani dan,',
          'Ti si i slatki moj san.',
          '',
          'Molim te, molim te, ljubav mi daj,',
          'Čekat će nas dvoje nebeski raj.',
          'Ja ću te dušo zagrliti,',
          'Sudbina neće nas rastaviti.',
          '',
          'Ti, ti si mi jedino sve,',
          'Ne mogu ja bez tebe.',
          'Snagu mi daješ, kad zadani dan,',
          'Ti si i slatki moj san.',
        ],
      },
    },
  },
  miSmoKajkavci: {
    title: 'Mi smo kajkavci (2007.)',
    tracks: {
      'tamburasko-kolo': {
        title: 'Tamburaško kolo',
        music: 'narodna',
      },
      'mi-smo-kajkavci': {
        title: 'Mi smo kajkavci',
        lyrics: 'J. Szallmer',
        music: 'J. Szallmer',
        text: [
          'Znajte, kaj morate znati,',
          'Nas je rodila kajkavska mati.',
          'Kad pjevamo, kad sviramo,',
          'Predake slavimo.',
          '',
          'Tuđa je zemlja primila nas,',
          'Utihnuo je naš glas.',
          "Al' opet se javljamo nek čuje svi,",
          'Da žive kajkavci!',
          '',
          "Puno sto godina j' prošlo,",
          'San nam čuvalo predivno jezero.',
          "Mislilo se, 'vak osamljeni,",
          'Moramo nestati.',
          '',
          'Tuđa je zemlja primila nas,',
          'Teški je bio taj čas.',
          'Novo smo rođeni, nek znaju svi,',
          'Da žive kajkavci!',
        ],
      },
      "cele-noci-'ladovina": {
        title: "Cele noći 'ladovina",
        music: 'narodna',
        text: [
          "Cele noći 'ladovina,",
          'Moje zlato spava.',
          "Cele noći 'ladovina,",
          'Moje zlato spava.',
          '',
          'Po jastuku ruke širi,',
          'O dragome sanja.',
          'Dođi dragi, zagrli me,',
          'Poludet ću sama.',
        ],
      },
      'cura-bere-cvijece': {
        title: 'Cura bere cvijeće',
        music: 'narodna',
        text: [
          'Cura bere cvijeće,',
          'A dragi je neće.',
          '',
          'On je majko bekrija,',
          'Bekrija i delija,',
          'On je majko sve.',
          '',
          'A šta će joj cvijeće,',
          'Kad je dragi neće.',
          '',
          'On je majko bekrija,',
          'Bekrija i delija,',
          'On je majko sve.',
          '',
          "Uzalud je tražit' u ljubavi sreću,",
          'Kad on vino pije, i danju i noću.',
          '',
          'On je majko bekrija,',
          'Bekrija i delija,',
          'On je majko sve.',
        ],
      },
      'da-mi-dano': {
        title: 'Da mi dano',
        music: 'narodna',
        text: [
          'Da mi dano dečke izbirati,',
          'Da mi dano dečke izbirati,',
          'Da mi dano dečke izbirati,',
          'Laj laj laj, la lala lalala.',
          '',
          'Ne bi znala, koga bi zibrala,',
          'Ne bi znala, koga bi zibrala,',
          'Ne bi znala, koga bi zibrala,',
          'Laj laj laj, la lala lalala.',
          '',
          'Umočana ne bi ni jednoga,',
          'Umočana ne bi ni jednoga,',
          'Umočana ne bi ni jednoga,',
          'Laj laj laj, la lala lalala.',
          '',
          'Umočani piju vino z lonci,',
          'Umočani piju vino z lonci,',
          'Umočani piju vino z lonci,',
          'Laj laj laj, la lala lalala.',
          '',
          'Umočanke piju z demižonke,',
          'Umočanke piju z demižonke,',
          'Umočanke piju z demižonke,',
          'Laj laj laj, la lala lalala.',
          '',
          'Kaj imaju, sve za vino daju,',
          'Kaj imaju, sve za vino daju,',
          'Kaj imaju, sve za vino daju,',
          'Laj laj laj, la lala lalala.',
        ],
      },
      'sad-cu-ti-povidat': {
        title: 'Sad ću ti povidat',
        music: 'narodna',
        text: [
          'Sad ću ti povidat,',
          'Svu istinu pravu,',
          'Da si već ne budeš',
          'Trapil tvoju glavu.',
          '',
          'Ne kaži se mili,',
          'Već po našoj strani,',
          'Ter mi tužno srce',
          'Jače ne narani.',
          '',
          'Dost sam suz točila,',
          'Nigdor nij htil znati,',
          'Nek moja družica',
          'Htila je poznati.',
        ],
      },
      'daleko-mi-je-biser-jadrana': {
        title: 'Daleko mi je biser Jadrana',
        music: 'narodna',
        text: [
          'Daleko mi je biser Jadrana,',
          'Daleko mi je moj rodni kraj.',
          'A još je dalje moja mila draga,',
          'Koju sam vjerno ljubio ja.',
          '',
          'Ja morem plovim, zvejdice brojim,',
          'I uvijek mislim na rodni kraj.',
          'Mladosti pun sam u nadi živim,',
          'Da ću te jednom viditi ja.',
          '',
          'Plovi mi, plovi, brodiću mali,',
          'Neka te prati sam božji dar.',
          'Ja mlađan suze vječito ronim,',
          'I uvijek mislim na rodni kraj.',
        ],
      },
      'evo-banke': {
        title: 'Evo banke',
        music: 'narodna',
        text: [
          'Evo banke, cigane moj, cigane moj, sviraj mi ti.',
          'Evo banke, cigane moj, cigane moj, sviraj mi ti.',
          'Ja ću tebi svirati, ti ćeš mene slušati.',
          'Evo banke, cigane moj, cigane moj, sviraj mi ti.',
          '',
          'Šampanj ćemo otvoriti, otvoriti i popiti.',
          'Rizling ćemo otvoriti, otvoriti i popiti.',
          'A kad dođe onaj čas, šampanj oborit će nas.',
          'Evo banke, cigane moj, cigane moj, sviraj mi ti.',
        ],
      },
      'nema-ljepse-djevojke': {
        title: 'Nema ljepše djevojke',
        music: 'M. Lengyel',
        lyrics: 'Z. Bogdan (M. Lengyel)',
        text: [
          'Nema ljepše djevojke,',
          'Ladi ladi lom, ladi ladi lom,',
          'Od Marike ciganke,',
          'Ladi ladi lom, ladi ladi lom.',
          '',
          'Kada pjeva tuguje, a kad igra luduje,',
          'I svako veče, kad prođem',
          'Kraj čarde svi pjevaju, lumpuju,',
          'Ladi ladi lom, ona pravi lom.',
        ],
      },
      'uzicko-kolo': { title: 'Užičko kolo', music: 'narodna' },
      'sinoc-bila-misecina': {
        title: 'Sinoć bila misečina',
        music: 'narodna',
        text: [
          'Sinoć bila misečina, a večeras tama.',
          'Sinoć bila misečina, a večeras tama.',
          'Odvedi me diko kući, nesmim ići sama.',
          'Odvedi me diko kući, nesmim ići sama.',
          '',
          'Aoj kćeri je to taj, hulja i bećar?',
          'Aoj kćeri je to taj, hulja i bećar?',
          "Jeste majko to je taj, al' nije bećar.",
          "Jeste majko to je taj, al' nije bećar.",
          '',
          'Ljubio sam curicu u šumi na panju.',
          'Ljubio sam curicu u šumi na panju.',
          'Kad nedaju po noći, a ja ću po danu.',
          'Kad nedaju po noći, a ja ću po danu.',
        ],
      },
      'gori-lampa-nasred-vinkovaca': {
        title: 'Gori lampa nasred Vinkovaca',
        music: 'narodna',
        text: [
          'Gori lampa nasred Vinkovaca,',
          'Dođi diko, bit će poljubaca.',
          'Oj, jadi, jadi,',
          'Jadi, jadi ne valja što radi.',
          '',
          'Sati biju ajziban se kreće,',
          'Ode moje mirisavo cvijeće.',
          'Oj, jadi, jadi,',
          'Jadi, jadi ne valja što radi.',
          '',
          'Sedam uri, ide lola curi,',
          'Ne voli je, pa se i ne žuri.',
          'Oj, jadi, jadi,',
          'Jadi, jadi ne valja što radi.',
          '',
          'Devet sati, ide lola Kati,',
          'Ide Kati, pa se i ne vrati.',
          'Oj, jadi, jadi,',
          'Jadi, jadi ne valja što radi.',
          '',
          'Diko moja, četiri su sata,',
          'Skidaj ruke sa mojega vrata.',
          'Oj, jadi, jadi,',
          'Jadi, jadi ne valja što radi.',
          '',
          'Pred zoru je lipo milovanje,',
          'Kad se mlađan spremam na oranje.',
          'Oj, diko moja,',
          'Diko moja, ljubim usta tvoja.',
        ],
      },
      'druzica-ljubljena': {
        title: 'Družica ljubljena',
        music: 'narodna',
        text: [
          'Družica ljubljena, dostala si druga,',
          'Razlučit se moraš od našega kruga.',
          '',
          'Veselu se danas tvoj otac i mati,',
          'Kad na tebi vidu zelen vijenac cvasti.',
          '',
          'A sad ti je došal jedan mili klinčac,',
          'Ki će ti razvezat tvoj zeleni vijenac.',
        ],
      },
      'kad-se-jutro-stanem': {
        title: 'Kad se jutro stanem',
        music: 'narodna',
        text: [
          'Kad se jutro stanem, s potkovicom ganem,',
          'Kad se jutro stanem, s potkovicom ganem.',
          'Stanem na travicu, stanem na travicu,',
          'Mislim na rožicu.',
          '',
          "Ta moja rožica dala me j' pozdravit,",
          "Ta moja rožica dala me j' pozdravit.",
          'A ja sam joj najzad, a ja sam joj najzad,',
          'Da ću ju ostavit.',
          '',
          'Ostavljaj se s mene a ja ću se s tebe,',
          'Ostavljaj se s mene a ja ću se s tebe.',
          'Ter ne dohajaj k nam, ter ne dohajaj k nam,',
          'Prik gore zelene.',
          '',
          'Prik gore zelene, a rožic rumene,',
          'Prik gore zelene, a rožic rumene.',
          'Ti si me ljubila, ti si me ljubila,',
          'Ja sam te za norca.',
          '',
          'Ko sam te za norca, mer si nisam oca,',
          'Ko sam te za norca, mer si nisam oca.',
          'Neg jednu rožicu, neg jednu rožicu,',
          'Folišnoga srca.',
        ],
      },
      'madarski-plesovi': { title: 'Mađarski plesovi', music: 'narodna' },
      'svecica-dogarja': {
        title: 'Svečica dogarja',
        music: 'narodna',
        text: [
          'Svečica dogarja,',
          'Polnoći dohaja,',
          'Pustite nas dragi oček,',
          'Da bi išle spat.',
          '',
          'Kudelja je mala,',
          'Špulica je puna,',
          'Pustite nas dragi oček,',
          'Da bi išle spat.',
          '',
          'Škornje sme zbrisale,',
          'K peči sme je dele,',
          'Pustite nas dragi oček,',
          'Da bi išle spat.',
        ],
      },
      madarac: { title: 'Mađarac', music: 'narodna' },
      kaj: {
        title: 'Kaj',
        lyrics: 'R. Taclik',
        music: 'D. Domjanić',
        text: [
          'Vretičeki spiju, a šume mučiju,',
          'Naj moja popevka zvoni.',
          'Po dolu i gaju, po dragome kraju,',
          'Od kojeg mi ljepšega ni.',
          '',
          'Tu brat mi je vsaki, tu doma sem taki,',
          'Pogodit bi mogel i speć.',
          'Poznati su puti, tu vsigje je čuti',
          'Ljubljenu domaću mi reč.',
          '',
          'I srce mi greje, i zmenom se smeje,',
          'I vžalosti plače takaj.',
          'Em nikaj ni slajše, ne čuje se rajše,',
          'Neg dobri i dragi naš kaj.',
        ],
      },
      'stara-tambura': {
        title: 'Stara tambura',
        lyrics: 'J. Szallmer',
        music: 'J. Szallmer',
        text: [
          'Ti si preživila sudbine,',
          'Tugu moju sakrila si dušo.',
          'Moje si srce razveselila,',
          'Kad si zasvirala.',
          '',
          'Sviraj mi, sviraj mi, tambura,',
          'Sviraj, dok živim ja.',
          'Ostani vjerna i najdraža,',
          'Najdraža jedina.',
          '',
          'Tvoje su žice zaplakale,',
          'Kad si zagledala suzno oko.',
          'Ona je mene nježno ljubila,',
          'Kad si zasvirala.',
          '',
          'Sviraj mi...',
          '',
          'Moju si dušu ti spasila,',
          'Kad je meni jednom teško bilo.',
          'Pjesmice sve si mi sačuvala,',
          'Kad si zasvirala.',
          '',
          'Sviraj mi...',
          '',
          'Kad tvoje sve žice zašute,',
          'Kad popuca tvoje drvo staro,',
          'Ostat će samo vječna sječanja,',
          'Kako si svirala.',
          '',
          'Sviraj mi...',
        ],
      },
    },
  },
  radujteSeNarodi: {
    title: 'Radujte se narodi (2006.)',
    tracks: {
      'tiha-noc': {
        title: 'Tiha noć',
        music: 'X. Gruber',
        lyrics: 'Joseph Mohr',
        text: [
          'Tiha noć, o sveta noć,',
          "Se j' va snu u polnoć.",
          'Nek jedina mat virostuje,',
          'Svoga sinka si usnihuje.',
          'Spavaj slatko sinak moj,',
          'Spavaj slatko sinak moj.',
          '',
          'Tiha noć, o sveta noć,',
          'Ča je to u polnoć.',
          "Rasvitljena j' pusta štalica,",
          "Ča j' to za dite va jaslica.",
          'Ko mlada majka dvori,',
          'Ko mlada majka dvori.',
          '',
          'Tiha noć, o sveta noć,',
          'Pastirom u polnoć.',
          'Od anđelov si nazvišćena,',
          'Čredu paseć kod Betlehema.',
          "Spasitelj vam se j' rodil,",
          "Spasitelj vam se j' rodil.",
        ],
      },
      'radujte-se-narodi': {
        title: 'Radujte se narodi',
        music: 'narodna',
        text: [
          'Radujte se narodi, kad čujete glas,',
          'Da se Isus porodi u blaženi čas.',
          'Svaki narod čuj, čuj, i Betlemu pristupljuj,',
          'Pristupljuj.',
          '',
          'Vidi Bože Otajstvo u podrtoj štalici,',
          'I tko trpi uboštvo na tvrdoj slamici.',
          'To Otajstvo čuj, čuj, i k jaslicam pristupljuj,',
          'Pristupljuj.',
          '',
          'Pođi i ti narode k betlemskome dvoru,',
          'Pridruži se klanjajuć anđeoskom koru.',
          'Lijepe dare daj, daj, pa mu ljepo zapjevaj,',
          'Zapjevaj!',
        ],
      },
      'setujte-pastiri': {
        title: 'Šetujte pastiri',
        music: 'narodna',
        text: [
          'Šetujte pastiri va Betlehem!',
          "Čudo se j' ovu noć stalo va njem!",
          'Ne štentajte nego pojte veljek,',
          'Onde Bog čeka vas iz veseljem.',
          '',
          'Narodil se je vam Zveličitelj,',
          'Dugoljet obećan Otkupitelj.',
          'Varošić znamenit David kralja,',
          'Mjesto mu je va njem vaša štala.',
          '',
          'Božji Sin vam leži v uski jasli,',
          'Med volom i oslom nek na slami.',
          'V tanjucke plenice mlada Majka,',
          "Radosno j' ovila svoga Sinka.",
        ],
      },
      'o-prekrasna-tajanstvena-noc': { title: 'O prekrasna tajanstvena noć', music: 'narodna' },
      'veselje-ti-navjescujem': {
        title: 'Veselje ti navješćujem',
        music: 'narodna',
        text: [
          'Veselje ti navješćujem, narod kršćanski,',
          'Jerbo se Kralj u Betlemu rodi nebeski.',
          'Još mali u štali, kog stvorenje svako slavi,',
          'Štuje, diči jer je pravi on naš Spasitelj i Otkupitelj.',
          '',
          'Pored njega stoji Majka, Djeva Marija,',
          'Pa sveg svijeta Spasitelja lijepo povija.',
          'Njeg doji i goji, uspavljuje njegujući:',
          '- Spavkaj, spavkaj - pjevajući - u toj štalici, sve na slamici!',
          '',
          'Majko Božja i Josipe, molite za nas,',
          'Koji smo se kod Betlema skupili danas,',
          'Daj da naše srdašce povoj bude Božjem Sinu,',
          'Isukrstu Gospodinu u vijeke, amen, u vijeke, amen!',
        ],
      },
      'o-pastiri-cudo-novo': {
        title: 'O pastiri, čudo, novo',
        music: 'narodna',
        text: [
          'O, pastiri, čudo novo,',
          'Niste nigda vidjeli ovo:',
          'U jaslicam prostim rodio se Bog,',
          'Koji s neba siđe radi puka svog.',
          'Koji s neba siđe radi puka svog.',
          '',
          'Betlem, evo, nije daleko,',
          'Znajte da vam istinu rekoh.',
          'U štalici prostoj leži Djetešce,',
          'Na slamici oštroj, kao janješce.',
          'Na slamici oštroj, kao janješce.',
          '',
          'Ljubav Božja prevelika,',
          'Primi pravu put čovjeka.',
          'S neba siđe dolje radi grešnika,',
          'Rodi se u štali radi čovjeka.',
          'Rodi se u štali radi čovjeka.',
        ],
      },
      'veseli-budmo': {
        title: 'Veseli budmo',
        music: 'narodna',
        text: [
          "Veseli budmo ar se j' rodil,",
          'Za kim je zdavno jur svit hlepil.',
          'Dite va krilu Majke, ko spi,',
          'Pravi je Kralj naš, Sin Božanski.',
          'Stupi va štalu pastir ubog,',
          'Spasit je došal nas mili Bog.',
          '',
          'Ne va palači spava svitloj,',
          'Ne na samitnoj stelji mehkoj,',
          'Mrzla su jasla i slamica,',
          'Blago mu grije mrzla lica.',
          'Prigni koljena vjerni kršćan,',
          'Ar je pred tobom Bog zmožni sam.',
          '',
          'Hodmo i mi sad pred njega,',
          'Boga zvišavat predragoga.',
          'Bijmo si srca pak skrušeno,',
          'Naše grihote uplačimo!',
          'Recimo: "Miluj nas Jezuše,',
          'Ki si otkupil grišne duše!"',
          '',
        ],
      },
      zvoncici: {
        title: 'Zvončići',
        lyrics: 'J. L. Pierpont',
        music: 'J. L. Pierpont',
        text: [
          'Dolove i brijeg, zabjelio je snijeg,',
          'Sa saona kroz noć naš se čuje smijeh.',
          'Pokićen i plah, naš vranac juri svud,',
          'A zvona dalek zvuk, pokazuje nam put.',
          '',
          'Zvončići, zvončići zvone cijelu noć,',
          'I ostaju u sječanju, što nikad neće proć.',
          'Zvončići, zvončići zvone naš sam glas',
          'Kroz tihu noć, čitav kraj, zvone za sve nas.',
          '',
          'Ponoć već je tu, za satom ide sat,',
          'Juri vranac naš, ko da nikad neće stat.',
          "Tiho pada snijeg, ko perje mek' i lak',",
          'Prijatelj je drag, veseli mu se svak.',
          '',
          'Zvončići, zvončići zvone cijelu noć,',
          'I ostaju u sječanju, što nikad neće proć.',
          'Zvončići, zvončići zvone naš sam glas',
          'Kroz tihu noć, čitav kraj, zvone za sve nas.',
          '',
          'Dolove i brijeg, zabjelio je snijeg,',
          'Sa saona kroz noć naš se čuje smijeh.',
          'Pokićen i plah, naš vranac juri svud,',
          'A zvona dalek zvuk, pokazuje nam put.',
          '',
          'Zvončići, zvončići zvone cijelu noć,',
          'I ostaju u sječanju, što nikad neće proć.',
          'Zvončići, zvončići zvone naš sam glas',
          'Kroz tihu noć, čitav kraj, zvone za sve nas.',
        ],
      },
      'ave-maria': { title: 'Ave Maria', music: 'J. S. Bach' },
    },
  },
  slatkeTajne: {
    title: 'Slatke tajne (2004.)',
    tracks: {
      'becarsko-kolo': { title: 'Bećarsko kolo', music: 'A. Nikolić' },
      'bijela-ruza': {
        title: 'Bijela ruža',
        music: 'narodna',
        text: [
          'Bijela ruža je procvala,',
          'Kad sam ja k tebi išal,',
          'I na tvoj mali obločić',
          'Mnogokrat sam pogledal.',
          '',
          'Hladna voda u potoku,',
          'Koja curi veselo.',
          'Ptičice slavno pjevaju,',
          'Kad se šećem krez selo.',
          '',
          'Ne stuguj nek bud vesela,',
          'Ja te ljubim, dobro znaš.',
          'To ti vidiš, vid na meni,',
          'Kada na me pogledaš.',
        ],
      },
      putna: { title: 'Putna', music: 'narodna' },
      'ribari-smo-sa-jadrana': {
        title: 'Ribari smo sa Jadrana',
        music: 'narodna',
        text: [
          'Kad plovimo u barci sve do zore,',
          'Riba nas prati kroz beskrajno more.',
          'A prid zoru, kad ugasu ferali,',
          'Prime nas opet tihi morski žali.',
          '',
          'Ribari smo sa Jadrana,',
          'Naša je ljubav u Splitu.',
          'Ribari smo sa Jadrana,',
          'Najlipšeg mora na svitu.',
          '',
          'Gitara prati nas od plave zore,',
          'I plovi s nama niz beskrajno more.',
          'A pri mrak opet palimo ferale,',
          'I ostavljamo tihe morske žale.',
          '',
          'Ribari smo sa Jadrana,',
          'Naša je ljubav u Splitu.',
          'Ribari smo sa Jadrana,',
          'Najlipšeg mora na svitu.',
        ],
      },
      'mila-majka-zac-si-me-ti-rodila': {
        title: 'Mila majka zač si me ti rodila',
        music: 'narodna',
        text: [
          'Mila majka, zač si me ti rodila,',
          'Zač me nisi va tu vodu hitila.',
          "Da b' ne bila o' ta voda odnesla,",
          "Ne b' se bila smanom rasturobila.",
          '',
          'Štuki grmu, ino flinke pucaju,',
          'Nas regrute sad va boj pozivaju.',
          'Da idemo domovinu braniti,',
          'Nepretelja preželjno obladati.',
          '',
          'Ti majkica, ti ležiš na steljici,',
          'A ja junak va zelenoj travici.',
          'Ti travica, ti si moja steljica,',
          'Ti kitica, ti si moja rožica.',
        ],
      },
      'djevojacko-kolo': { title: 'Djevojačko kolo', music: 'narodna' },
      'kakve-cura-crne-oci-ima': {
        title: 'Kakve cura crne oči ima',
        music: 'narodna',
        text: [
          'Bijelo cviće svu noć cvalo, rado bi se bralo.',
          'Crne oči svu noć sjale, kome bi se dale.',
          'Što će meni crne oči, kad su puste moje noći,',
          'Crne oči kao tama, a ja spavam sama.',
          '',
          'Ponoć prođe, brojim sate, stalno mislim na te.',
          'Svu noć srce doček sprema, ali dragog nema.',
          'Što će meni jastuk bijeli, kad mi nema, kog da želim.',
          'Jastuk bijeli, bijeli zubi, nema ko da ljubi.',
        ],
      },
      tandora: {
        title: 'Tandora',
        music: 'narodna',
        text: [
          "Tan tan tandora, sjela cura pod ora',",
          "Tan tan tandora, sjela cura pod ora'.",
          'Sjela cura pa šije, prid njom litra rakije,',
          'Sjela cura pa šije, prid njom litra rakije.',
          '',
          'Tan tan tandora, nema cura lavora,',
          'Tan tan tandora, nema cura lavora.',
          'Nema cura kopanje, pa iskala od Franje,',
          'Nema cura kopanje, pa iskala od Franje.',
          '',
          "Tan tan tandora, sjela cura pod ora',",
          "Tan tan tandora, sjela cura pod ora'.",
          'Sjela cura na vreću, svi je ljube, ja neću,',
          'Sjela cura na vreću, svi je ljube, ja neću.',
        ],
      },
      svatovac: { title: 'Svatovac', music: 'narodna' },
      'slavonijo---zemljo-plemenita': {
        title: 'Slavonijo - zemljo plemenita',
        music: 'narodna',
        text: [
          'Ej Slavonijo, zemljo plemenita,',
          "Puna žitni' polja, valovita.",
          "Šorom, šorom, 'ladom, idem diki kradom.",
          "Šorom, šorom, 'ladom, idem diki kradom.",
          '',
          'Ej sedam bora, do dikina dvora,',
          'A do moga nema ni jednoga.',
          "Šorom, šorom, 'ladom, idem diki kradom.",
          "Šorom, šorom, 'ladom, idem diki kradom.",
          '',
          'Ej ljubičice, ne cvati na brigu.',
          'Već u doli, di se dvoje voli.',
          "Šorom, šorom, 'ladom, idem diki kradom.",
          "Šorom, šorom, 'ladom, idem diki kradom.",
        ],
      },
      'slavonkso-djevojacko-kolo': { title: 'Slavonsko djevojačko kolo', music: 'narodna' },
      'ternjice-ternjice': {
        title: 'Ternjice, ternjice',
        music: 'narodna',
        text: [
          'Ternjice, ternjice, med ternjicem šipak,',
          "Poglejte rožice kako j' vo lip žitak.",
          'Lip žitak, lip žitak, ki ga ferat znaju mila moja,',
          'Ki ga ferat znaju.',
          '',
          'Rožicam selo pojt, seli bit do zore,',
          'Rožicam selo pojt, seli bit do zore.',
          'A u bijeloj zori onde smo postali mila moja,',
          'Onde smo postali.',
          '',
          'I jedan drugomu, lafku noć zazvali,',
          'I jedan drugomu, lafku noć zazvali.',
          'Lafku noć, lafku noć, ovo ti je ruka mila moja,',
          'Ovo ti je ruka.',
        ],
      },
      'posavski-drmes': { title: 'Posavski drmeš', music: 'narodna' },
      'bolujem-ja': {
        title: 'Bolujem ja',
        music: 'narodna',
        text: [
          'Bolujem ja, boluješ ti,',
          'Bolujemo od ljubavi.',
          'Jer nikoga ne ljubim ja,',
          'Samo tebe, dušo moja.',
          '',
          'Otvori mi taj prozor tvoj,',
          'Da ti kažem, anđele moj.',
          'Da nikoga ne ljubim ja,',
          'Osim tebe, dušo moja.',
          '',
          'Otići ću u dalek svijet,',
          'Da potražim mom srcu lijek.',
          'Jer nikoga ne ljubim ja,',
          'Kao tebe, dušo moja.',
        ],
      },
      'predragi-narode-moj': {
        title: 'Predragi narode moj',
        lyrics: 'J. Szallmer',
        music: 'J. Szallmer',
        text: [
          'Prođem kroz rodno mi selo,',
          'Nekad prekrasno, veselo.',
          'Tražim te, kućice bijele,',
          'Pred njima ruže rumene.',
          '',
          'Sjećam se konje i kola,',
          'Šuštenja reda topola.',
          'Mirisno sjeno i štale,',
          'Vesele divojke male.',
          '',
          'Kud ste mi dragi hrvati,',
          'Prijatelji, moji stari?',
          'Gdje ste, ostale mi pjesme,',
          'Majcine rječi sad gdje ste?',
          '',
          'Nema svrake koja se kara,',
          'Nije naša ni gora stara.',
          'Va crikvi rijetko se pjeva',
          'Ta prekrasna rajska djeva.',
          '',
          'Osjećam, došlo je doba,',
          'Stigli smo i mi do groba.',
          'Predragi narode moj,',
          'Čeka te vječni pokoj!',
        ],
      },
    },
  },
};
